FROM python:3.13-slim

WORKDIR /ecommerce-fraud

COPY requirements.txt ./requirements.txt

RUN pip install --no-cache-dir --upgrade -r ./requirements.txt

COPY ./src ./src
COPY ./models ./models
COPY ./data ./data 
COPY ./api ./api
COPY ./training ./training

CMD ["uvicorn", "api.main:app", "--host", "0.0.0.0", "--port", "8000"]
