FROM python:3.13-slim

WORKDIR /ecommerce-fraud

COPY requirements.txt ./requirements.txt

RUN pip install --no-cache-dir --upgrade -r ./requirements.txt

COPY ./app.py ./app.py
COPY ./src ./src

CMD ["streamlit", "run", "app.py", "--server.port=8501", "--server.address=0.0.0.0"]